import type { Metadata } from "next";
import Link from "next/link";
import { Suspense } from "react";
import { BrandMarkIcon } from "../components/brand-mark.js";
import { installUrl, LandingHeroActions, LandingNavActions } from "../components/landing-actions.js";
import { PublicStructuredData } from "../components/public-structured-data.js";
import { ThemeToggle } from "../components/theme-toggle.js";
import { buttonVariants } from "../components/ui/button.js";

export const metadata: Metadata = {
  title: { absolute: "BoardReadyOps — Know what stands between your board and production." },
  description: "Checks whether a hardware board is ready to fabricate, on every pull request.",
  alternates: {
    canonical: "/",
    types: {
      "text/markdown": "/index.md",
    },
  },
};

const proofItems = [
  "Layout and schematic rule checks",
  "Parts you can actually buy",
  "A complete manufacturing package",
  "Every result tied to a file and a checksum",
] as const;

const workflowSteps = [
  {
    number: "01",
    title: "Connect the repository",
    body: "Install the GitHub App. Your source, branch protection and workflow history stay where they are.",
  },
  {
    number: "02",
    title: "Check the exact commit",
    body: "KiCad, BOM and manufacturing checks run against the commit in the pull request, not a moving branch.",
  },
  {
    number: "03",
    title: "Decide before you order",
    body: "Start with the verdict, then open the findings, files and execution history behind it.",
  },
] as const;

const glossaryTerms = [
  {
    term: "DRC",
    definition:
      "Design Rule Check. KiCad checks board geometry such as clearances, widths, keepouts, and connectivity against the rules defined by the project. BoardReadyOps keeps the resulting evidence tied to the exact commit being reviewed instead of treating a local DRC run as timeless proof. Track clearances, annular rings, track widths, hole sizes, and microvia rules across all copper layers deterministically.",
  },
  {
    term: "ERC",
    definition:
      "Electrical Rules Check. ERC catches schematic-level problems such as incompatible pin types, missing drivers, and unconnected signals. It complements DRC: a board can be geometrically clean while the schematic still contains an electrical contradiction that should block release. Pin-to-pin directionality, power supply conflicts, floating inputs, and netlabel mismatches are surfaced before tapeout.",
  },
  {
    term: "BOM",
    definition:
      "Bill of materials. BoardReadyOps evaluates the part list that belongs to the release, including manufacturer part numbers, lifecycle signals, variant consistency, approved alternates, and evidence that the selected parts match the design being handed off. It guards against obsolete silicon, unpopulated references, ambiguous packaging codes, and out-of-stock components before placement.",
  },
  {
    term: "Manufacturing package",
    definition:
      "The fabrication and assembly deliverables required by the chosen handoff: Gerbers, drill data, BOM, position files, and drawings. BoardReadyOps can generate these through boardreadyops generate (wrapping kicad-cli) or validate the outputs generated by your existing toolchain. Each package manifest guarantees that all layers, drill files, and pick-and-place lists correspond to identical source revisions.",
  },
  {
    term: "Release evidence",
    definition:
      "Versioned facts used to justify a hardware release decision: check results, manifests, hashes, reports, workflow runs, and manufacturing outputs. Evidence is useful only when a reviewer can trace it back to the exact source revision and see whether it is still current. Every verification assertion records timestamp, Git commit SHA, exit status, and SHA-256 artifact signatures.",
  },
  {
    term: "Check Run",
    definition:
      "GitHub's native status-and-detail record for a commit. BoardReadyOps publishes a concise readiness conclusion there, then links deeper findings and artifacts so an engineer can start with the decision without losing the audit trail behind it. Annotations appear inline on changed layout or schematic files so hardware reviewers stay in their core pull request workflow.",
  },
  {
    term: "Exact-commit evaluation",
    definition:
      "The rule that every release decision must identify the immutable Git commit it evaluated. A moving branch name is not enough: if the branch changes after a check begins, the evidence remains attached to the original revision rather than silently describing different source. This guarantees reproducible fabrication audits across distributed hardware engineering teams.",
  },
  {
    term: "CPL / position file",
    definition:
      "The component placement list used by an assembler to place parts on the PCB. Coordinates, rotation, side, reference designators, and package identity need to agree with the released board and BOM; stale placement data can make an otherwise clean design impossible to assemble correctly. BoardReadyOps verifies pin 1 rotation conventions and coordinate origins across SMD footprints.",
  },
  {
    term: "Waiver",
    definition:
      "An explicit, reviewable decision to accept a known finding under defined conditions. BoardReadyOps treats waivers as evidence with scope and history, not as a way to erase a warning from the record. The underlying finding remains understandable to future reviewers, carrying author justification, expiration parameters, and project owner sign-off.",
  },
  {
    term: "Source of truth",
    definition:
      "The protected repository commit and its GitHub workflow evidence. BoardReadyOps presents and normalizes that evidence, but the repository, pull request, Check Run, workflow history, and versioned files remain authoritative for what was reviewed and released. No external database overrides what the cryptographic Git log proves.",
  },
  {
    term: "Gerbers (RS-274X & X2)",
    definition:
      "The standard vector artwork format for printed circuit board fabrication, describing copper conductors, solder mask openings, silkscreen legends, and mechanical outlines. BoardReadyOps inspects layer assignments, aperture macros, coordinate precision, and perimeter continuity to prevent manufacturing delays at the PCB fabrication plant.",
  },
  {
    term: "IPC-2581 & ODB++",
    definition:
      "Intelligent manufacturing data exchange formats consolidating layer stackup, drill definitions, component placement data, and electrical netlists into a single digital container. BoardReadyOps validates schema conformance and cross-checks layer definitions against board physical stackup parameters.",
  },
  {
    term: "Annular Ring & Drill Breakout",
    definition:
      "The margin of copper pad surrounding a drilled via or through-hole lead. Inadequate annular ring width risks drill breakout during multi-layer board lamination, leading to intermittent opens or impedance discontinuities. Automated checks ensure all plated holes respect fabricator minimum annular tolerances.",
  },
  {
    term: "Solder Mask Dam & Web Clearance",
    definition:
      "The minimum physical bridge of solder mask material between adjacent surface mount pads. Missing or undersized solder mask webs cause solder bridging and short circuits during convection reflow assembly. BoardReadyOps catches tight-pitch pad clearances that violate vendor mask capability.",
  },
  {
    term: "Impedance & Layer Stackup",
    definition:
      "Controlled dielectric heights, copper weights, and trace geometries required for high-speed differential pairs, USB, Ethernet, and RF routing. Release validation verifies that PCB stackup tables in drawings match the physical layer definitions exported in Gerber and drill archives.",
  },
] as const;

const releaseGuides = [
  {
    title: "Why an exact commit matters",
    body: "Hardware reviews are often longer than software checks. A BOM can be refreshed, a footprint moved, or a fabrication output regenerated while somebody is still looking at the pull request. BoardReadyOps records the commit and workflow context that produced a result so a later change cannot inherit an earlier green decision by accident. When a new commit appears, it deserves new evidence. That keeps the question simple: the verdict on screen describes this revision, not a nearby version of the board. Every check run cryptographically binds its findings, logs, and generated fabrication archives to the specific Git commit SHA.",
  },
  {
    title: "Evidence stays close to the engineering workflow",
    body: "The useful place for a release decision is where engineers already review change: the pull request and its GitHub checks. The Check Run carries the short conclusion; findings explain what needs attention; artifacts and hashes show which generated outputs were evaluated; workflow logs preserve execution context. BoardReadyOps is deliberately not a replacement repository. It creates a navigable decision trail over evidence that remains owned by the project. Reviewers can triage DRC violations, verify component replacements, and audit signoffs without switching context.",
  },
  {
    title: "Manufacturing readiness is broader than DRC and ERC",
    body: "A clean schematic and layout are necessary, but they do not prove that a contract manufacturer received a usable package. The release also needs the expected Gerbers and drill files, a BOM that matches the selected variant, component placement data, useful fabrication notes, and any project-specific vendor requirements. BoardReadyOps brings those checks into one release-readiness view so missing handoff evidence is visible before an order is placed. Verifying component availability, lead times, pin 1 orientation, and drill drawing notes prevents expensive fabrication scrap.",
  },
  {
    title: "Repository control remains explicit",
    body: "The production GitHub App is intentionally narrow. Repository-owned configuration and workflow files go through the same protected pull-request process as the board itself. BoardReadyOps can report a decision and dispatch the repository-owned evaluation workflow, but it does not quietly rewrite design files or bypass branch protection. That boundary makes a green result easier to trust because the automation cannot change the source in order to make its own check pass. Your team maintains total control over design rules and fabrication tolerances.",
  },
  {
    title: "Automated release gates replace brittle manual spreadsheets",
    body: "Traditional hardware handoffs rely on manual checklists, tribal knowledge, and error-prone spreadsheet reviews that slip under release deadlines. BoardReadyOps formalizes hardware release policies into repeatable CI/CD pipelines. Every pull request executes deterministic DRC, ERC, netlist comparison, BOM validation, and Gerber completeness checks in an isolated environment. The result is documented, auditable compliance before money is committed to copper, tooling, and surface-mount assembly.",
  },
] as const;

const releaseFaq = [
  {
    question: "Does BoardReadyOps generate the manufacturing files?",
    answer:
      "You can generate them with BoardReadyOps or bring your own. Use 'boardreadyops generate' to produce Gerbers, drill files, BOM, and position files directly via kicad-cli, or keep your existing KiBot/export pipeline. BoardReadyOps validates that the package is complete, current, and matches the evaluated commit before you order boards. It verifies layer counts, drill tool tables, format versions, and checksum manifests against your specified fabrication profile.",
  },
  {
    question: "When should a release check run again?",
    answer:
      "Whenever the source revision or evidence that supports the decision changes. A footprint edit, BOM substitution, regenerated fabrication archive, policy change, or new commit can change the release conclusion. The exact-commit model makes that boundary visible: an older green Check Run remains a record of what it evaluated, but it is not silently promoted to evidence for a different revision. Branch changes immediately invalidate prior stamps.",
  },
  {
    question: "How should a reviewer interpret a waiver?",
    answer:
      "A waiver is a documented engineering decision, not a deleted finding. Reviewers should be able to see what was waived, why the exception was accepted, which scope it applies to, and whether the underlying condition still exists. That makes temporary manufacturing exceptions and known design tradeoffs auditable without teaching the automation to ignore the problem forever. Each waiver retains author identity, commit context, and rationale.",
  },
  {
    question: "What makes a manufacturing handoff reviewable later?",
    answer:
      "The handoff needs more than a folder of outputs. It needs a traceable source revision, a manifest or equivalent inventory, hashes for important files, the policy that was evaluated, and a workflow record showing how the evidence was produced and checked. BoardReadyOps organizes those facts around the release decision so another engineer can reconstruct why the board was considered ready without relying on somebody's local workstation state. Audit logs preserve the complete verification trail.",
  },
  {
    question: "How does BoardReadyOps verify schematic and layout synchronization?",
    answer:
      "BoardReadyOps extracts electrical netlists from both the schematic (via kicad-cli or eeschema exports) and the routed PCB layout (via pcbnew exports) and performs a deep structural netlist comparison. Any pin disconnect, unintended net merger, swapped differential polarity, or missing pull-up resistor triggers a blocking finding with exact component designators and schematic sheet references.",
  },
] as const;

const releaseEvidenceChecklist = [
  {
    title: "Source revision",
    body: "Record the immutable Git commit that the decision describes. A branch name can move after review starts; the release evidence must not.",
  },
  {
    title: "Design checks",
    body: "Keep DRC and ERC results associated with the evaluated project so schematic and layout findings can be traced to the same revision as the handoff.",
  },
  {
    title: "Manufacturing outputs",
    body: "Verify that expected Gerbers, drill data, BOM, CPL or position files, drawings, and configured vendor deliverables are present and current rather than leftovers from an older build.",
  },
  {
    title: "Evidence identity",
    body: "Use manifests, hashes, or equivalent identifiers for important artifacts. A reviewer should be able to tell which exact output was checked without trusting a filename alone.",
  },
  {
    title: "Policy and exceptions",
    body: "Preserve the release policy, blocking threshold, suppressions, and waivers that shaped the verdict. Exceptions should remain visible engineering decisions with scope and rationale.",
  },
  {
    title: "Workflow record",
    body: "Keep the GitHub workflow and Check Run that produced the result. Together they show when the evaluation ran, which revision it evaluated, and where a reviewer can inspect the authoritative execution evidence.",
  },
] as const;

const capabilities = [
  {
    eyebrow: "Design",
    title: "Layout and schematic",
    body: "Every rule violation stays attached to the commit that introduced it.",
  },
  {
    eyebrow: "Supply chain",
    title: "Bill of materials",
    body: "Missing part numbers, parts going end of life, and gaps between variants — before handoff.",
  },
  {
    eyebrow: "Manufacturing",
    title: "Manufacturing readiness",
    body: "Gerbers, drill files, markings and assembly outputs, checked for completeness.",
  },
  {
    eyebrow: "Traceability",
    title: "Nothing unaccounted for",
    body: "Every result traces back to a versioned file, its checksum, and the workflow run that produced it.",
  },
  {
    eyebrow: "Speed",
    title: "Fast on a long history",
    body: "Search, filter and sort without waiting for your whole history to load.",
  },
  {
    eyebrow: "Publication",
    title: "It all lives in GitHub",
    body: "Check Runs, pull requests and workflow logs stay in GitHub. No second place to look.",
  },
] as const;

export default function HomePage() {
  return (
    <div className="bg-background text-foreground">
      <PublicStructuredData />
      <a
        className="absolute left-2 top-2 z-50 -translate-y-16 rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground focus:translate-y-0"
        href="#main-content"
      >
        Skip to main content
      </a>

      <header className="sticky top-0 z-40 flex items-center justify-between border-b border-border bg-background/95 px-6 py-4 backdrop-blur">
        <Link
          href="/"
          className="flex items-center gap-2 text-sm font-bold text-foreground"
          aria-label="BoardReadyOps home"
        >
          <BrandMarkIcon size={24} />
          <span>BoardReadyOps</span>
        </Link>
        <nav aria-label="Global navigation" className="flex items-center gap-6 text-sm">
          <a href="#product" className="text-muted-foreground hover:text-foreground">
            Product
          </a>
          <a href="#how-it-works" className="text-muted-foreground hover:text-foreground">
            How it works
          </a>
          <a href="#glossary" className="text-muted-foreground hover:text-foreground">
            Glossary
          </a>
          <a
            href="https://docs.boardreadyops.com/security/assurance-case/"
            className="text-muted-foreground hover:text-foreground"
          >
            Trust
          </a>
          <a href="https://docs.boardreadyops.com" className="text-muted-foreground hover:text-foreground">
            Docs
          </a>
          <ThemeToggle variant="button" />
          {/* Suspended so reading the session never delays the landing navigation. */}
          <Suspense fallback={null}>
            <LandingNavActions />
          </Suspense>
        </nav>
      </header>

      <main id="main-content">
        <section className="border-b border-border py-20" aria-labelledby="landing-heading">
          <div className="mx-auto grid max-w-6xl grid-cols-1 gap-12 px-6 lg:grid-cols-[3fr_2fr] lg:items-center">
            <div>
              <p className="text-sm font-medium text-primary">Hardware release intelligence for every CAD workflow</p>
              <h1 id="landing-heading" className="mt-3 text-4xl font-bold leading-tight text-foreground sm:text-5xl">
                Know what stands between your board and production.
              </h1>
              <p className="mt-4 text-lg text-muted-foreground">
                BoardReadyOps checks whether your board is ready to fabricate on every pull request — or right from your
                local terminal. One verdict, clear blockers, and verifiable release evidence.
              </p>
              <div className="mt-6 flex flex-wrap items-center gap-3">
                <Suspense
                  fallback={
                    <a className={`${buttonVariants({ variant: "default", size: "lg" })} gap-2`} href={installUrl}>
                      <span>Install on GitHub</span>
                      <span aria-hidden="true">↗</span>
                    </a>
                  }
                >
                  <LandingHeroActions />
                </Suspense>
              </div>
              <ul
                className="mt-6 flex flex-wrap gap-x-6 gap-y-2 text-sm text-muted-foreground"
                aria-label="What BoardReadyOps does"
              >
                <li>Local CLI or GitHub Actions</li>
                <li>Clear blockers before you order</li>
                <li>Your repository stays in charge</li>
              </ul>
            </div>

            <aside className="rounded-md border border-border bg-card p-5 shadow-lg" aria-label="What a run looks like">
              <div className="flex items-center gap-2 text-xs text-muted-foreground">
                <span className="size-2 rounded-full bg-success" aria-hidden="true" />
                <span>Sample review · USB-C Sensor Node v2.1</span>
                <code className="ml-auto rounded-sm bg-muted px-1.5 py-0.5">sample-pull-request</code>
              </div>
              <div className="mt-4 flex items-center justify-between gap-3">
                <div>
                  <span className="block text-xs uppercase text-muted-foreground">The verdict</span>
                  <strong className="text-base text-foreground">Ready to fabricate</strong>
                </div>
                <span className="rounded-full bg-muted px-2 py-0.5 text-xs text-foreground">Resolved after rerun</span>
              </div>
              <ol className="mt-4 flex flex-col gap-3">
                <li className="flex items-center gap-3">
                  <span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-muted text-xs font-bold text-foreground">
                    01
                  </span>
                  <div className="flex-1">
                    <strong className="block text-sm text-foreground">Inspect release decision</strong>
                    <span className="text-xs text-muted-foreground">Exact revision, branch, and Check Run</span>
                  </div>
                  <span className="text-xs text-muted-foreground">Pinned</span>
                </li>
                <li className="flex items-center gap-3">
                  <span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-muted text-xs font-bold text-foreground">
                    02
                  </span>
                  <div className="flex-1">
                    <strong className="block text-sm text-foreground">What it found</strong>
                    <span className="text-xs text-muted-foreground">
                      Layout, schematic, BOM, and manufacturing checks
                    </span>
                  </div>
                  <span className="text-xs text-muted-foreground">Explained</span>
                </li>
                <li className="flex items-center gap-3">
                  <span className="flex size-6 shrink-0 items-center justify-center rounded-full bg-muted text-xs font-bold text-foreground">
                    03
                  </span>
                  <div className="flex-1">
                    <strong className="block text-sm text-foreground">The files it produced</strong>
                    <span className="text-xs text-muted-foreground">Reports and outputs, each with a checksum</span>
                  </div>
                  <span className="text-xs text-muted-foreground">Downloadable</span>
                </li>
              </ol>
              <p className="mt-4 text-xs text-muted-foreground">
                Illustrative sample. Your repository and its workflow logs stay the source of truth.
              </p>
            </aside>
          </div>
        </section>

        <section className="border-b border-border py-16" aria-labelledby="proof-heading">
          <div className="mx-auto grid max-w-6xl grid-cols-1 gap-10 px-6 lg:grid-cols-[1fr_1fr] lg:items-start">
            <div className="flex flex-col gap-2">
              <p className="text-sm font-medium text-primary">Pull request evidence</p>
              <h2 id="proof-heading" className="text-2xl font-bold text-foreground sm:text-3xl">
                Every pull request, reviewed like a design review.
              </h2>
              <p className="text-sm text-muted-foreground">
                DRC, ERC, BOM and manufacturing checks arrive as one answer instead of several logs, and every part of
                it links back to the GitHub run it came from.
              </p>
            </div>
            <ul className="grid grid-cols-1 gap-4 sm:grid-cols-2">
              {proofItems.map((item, index) => (
                <li key={item} className="flex items-start gap-3">
                  <span className="text-2xl font-bold text-muted-foreground">{String(index + 1).padStart(2, "0")}</span>
                  <strong className="pt-1 text-sm text-foreground">{item}</strong>
                </li>
              ))}
            </ul>
          </div>
        </section>

        <section className="border-b border-border py-16" id="how-it-works" aria-labelledby="workflow-heading">
          <div className="mx-auto max-w-6xl px-6">
            <div className="flex max-w-2xl flex-col gap-2">
              <p className="text-sm font-medium text-primary">Release workflow</p>
              <h2 id="workflow-heading" className="text-2xl font-bold text-foreground sm:text-3xl">
                From design change to release decision.
              </h2>
              <p className="text-sm text-muted-foreground">
                Keep the engineering path short: connect, evaluate, investigate.
              </p>
            </div>
            <ol className="mt-8 grid grid-cols-1 gap-6 sm:grid-cols-3">
              {workflowSteps.map((step) => (
                <li key={step.number} className="flex flex-col gap-2">
                  <span className="text-3xl font-bold text-muted-foreground">{step.number}</span>
                  <div>
                    <h3 className="text-base font-bold text-foreground">{step.title}</h3>
                    <p className="mt-1 text-sm text-muted-foreground">{step.body}</p>
                  </div>
                </li>
              ))}
            </ol>
          </div>
        </section>

        <section className="border-b border-border py-16" id="product" aria-labelledby="control-room-heading">
          <div className="mx-auto max-w-6xl px-6">
            <div className="flex max-w-2xl flex-col gap-2">
              <p className="text-sm font-medium text-primary">What you see</p>
              <h2 id="control-room-heading" className="text-2xl font-bold text-foreground sm:text-3xl">
                The answer first. The reasons underneath.
              </h2>
              <p className="text-sm text-muted-foreground">
                Open a run and the verdict is the first thing on the page. Everything below it is there to explain that
                verdict, or to let you argue with it.
              </p>
            </div>

            <div className="mt-8 rounded-md border border-border bg-card p-6">
              <header className="flex flex-wrap items-center justify-between gap-3 border-b border-border pb-4">
                <div>
                  <span className="block text-xs uppercase text-muted-foreground">Investigation</span>
                  <strong className="text-sm text-foreground">repository / release revision</strong>
                </div>
                <ul className="flex gap-2">
                  <li className="rounded-full bg-muted px-2 py-0.5 text-xs text-foreground">Decision first</li>
                  <li className="rounded-full bg-muted px-2 py-0.5 text-xs text-muted-foreground">Loads fast</li>
                </ul>
              </header>
              <div className="grid grid-cols-1 gap-4 pt-4 lg:grid-cols-3">
                <article className="rounded-md border border-primary/40 bg-accent/30 p-4">
                  <span className="text-xs uppercase text-muted-foreground">Decision first</span>
                  <h3 className="mt-1 text-base font-bold text-foreground">
                    Shortest next action before low-level evidence.
                  </h3>
                  <p className="mt-1 text-sm text-muted-foreground">
                    See the stable readiness result, blocking state, and direct path to the evidence that can change the
                    release decision.
                  </p>
                  <div className="mt-3 flex flex-col gap-2" aria-hidden="true">
                    <span className="w-fit rounded-sm bg-muted px-2 py-1 text-xs text-foreground">
                      Review blocking findings
                    </span>
                    <span className="w-fit rounded-sm bg-muted px-2 py-1 text-xs text-foreground">
                      Verify release evidence
                    </span>
                  </div>
                </article>
                <article className="rounded-md border border-border p-4">
                  <span className="text-xs uppercase text-muted-foreground">Finding things</span>
                  <h3 className="mt-1 text-base font-bold text-foreground">
                    Search what matters, not everything you have ever run.
                  </h3>
                  <p className="mt-1 text-sm text-muted-foreground">
                    Filter findings and files without pulling your whole history down the wire.
                  </p>
                </article>
                <article className="rounded-md border border-border p-4">
                  <span className="text-xs uppercase text-muted-foreground">Back to the source</span>
                  <h3 className="mt-1 text-base font-bold text-foreground">
                    Every answer links back to where it came from.
                  </h3>
                  <p className="mt-1 text-sm text-muted-foreground">
                    One click to the commit, the Check Run, the workflow run, the pull request, or the file itself.
                  </p>
                </article>
              </div>
            </div>
          </div>
        </section>

        <section className="border-b border-border py-16" aria-labelledby="capabilities-heading">
          <div className="mx-auto max-w-6xl px-6">
            <div className="flex max-w-2xl flex-col gap-2">
              <p className="text-sm font-medium text-primary">Engineering coverage</p>
              <h2 id="capabilities-heading" className="text-2xl font-bold text-foreground sm:text-3xl">
                Every check stays tied to the commit it ran on.
              </h2>
              <p className="text-sm text-muted-foreground">
                Layout, supply chain and manufacturing all reported the same way, so nothing needs translating.
              </p>
            </div>
            <div className="mt-8 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {capabilities.map((capability) => (
                <article key={capability.title} className="rounded-md border border-border bg-card p-4">
                  <span className="text-xs uppercase text-muted-foreground">{capability.eyebrow}</span>
                  <h3 className="mt-1 text-base font-bold text-foreground">{capability.title}</h3>
                  <p className="mt-1 text-sm text-muted-foreground">{capability.body}</p>
                </article>
              ))}
            </div>
          </div>
        </section>

        <section className="border-b border-border py-16" aria-labelledby="trust-heading">
          <div className="mx-auto grid max-w-6xl grid-cols-1 gap-10 px-6 lg:grid-cols-[3fr_2fr] lg:items-start">
            <div className="flex flex-col gap-2">
              <p className="text-sm font-medium text-primary">Trust boundary</p>
              <h2 id="trust-heading" className="text-2xl font-bold text-foreground sm:text-3xl">
                Your repository stays the source of truth.
              </h2>
              <p className="text-sm text-muted-foreground">
                BoardReadyOps reads and reports; it does not take custody of anything. Your source, branch protections,
                pull requests, checks and full workflow logs stay in the repository you already run.
              </p>
            </div>
            <dl className="grid grid-cols-1 gap-4 sm:grid-cols-3">
              <div>
                <dt className="text-xs uppercase text-muted-foreground">Source of truth</dt>
                <dd className="mt-1 text-sm text-foreground">
                  Repository commit and protected GitHub workflow evidence
                </dd>
              </div>
              <div>
                <dt className="text-xs uppercase text-muted-foreground">Investigation</dt>
                <dd className="mt-1 text-sm text-foreground">
                  Findings and file details only — never your board design itself
                </dd>
              </div>
              <div>
                <dt className="text-xs uppercase text-muted-foreground">Decision trail</dt>
                <dd className="mt-1 text-sm text-foreground">
                  Check Run, publication state, attempts, checksums, and audit boundary
                </dd>
              </div>
            </dl>
          </div>
        </section>

        <section className="border-b border-border py-16" aria-labelledby="release-guide-heading">
          <div className="mx-auto max-w-6xl px-6">
            <div className="flex max-w-2xl flex-col gap-2">
              <p className="text-sm font-medium text-primary">How to read a release decision</p>
              <h2 id="release-guide-heading" className="text-2xl font-bold text-foreground sm:text-3xl">
                Evidence is useful when another engineer can reproduce the reasoning.
              </h2>
              <p className="text-sm text-muted-foreground">
                BoardReadyOps is built around a small set of release principles that make hardware evidence easier to
                review now and easier to audit later.
              </p>
            </div>
            <div className="mt-8 grid grid-cols-1 gap-6 sm:grid-cols-2">
              {releaseGuides.map((guide) => (
                <article key={guide.title}>
                  <h3 className="text-base font-bold text-foreground">{guide.title}</h3>
                  <p className="mt-1 text-sm text-muted-foreground">{guide.body}</p>
                </article>
              ))}
            </div>
            <section
              className="mt-10 rounded-md border border-border bg-card p-6"
              aria-labelledby="evidence-checklist-heading"
            >
              <h3 id="evidence-checklist-heading" className="text-base font-bold text-foreground">
                A reviewable release-evidence checklist
              </h3>
              <p className="mt-1 text-sm text-muted-foreground">
                A green verdict should be explainable without access to the original engineer's workstation. These are
                the evidence categories a reviewer should expect to trace.
              </p>
              <ol className="mt-4 flex list-decimal flex-col gap-2 pl-5 text-sm">
                {releaseEvidenceChecklist.map((entry) => (
                  <li key={entry.title}>
                    <strong className="text-foreground">{entry.title}</strong>{" "}
                    <span className="text-muted-foreground">{entry.body}</span>
                  </li>
                ))}
              </ol>
            </section>

            <div className="mt-10">
              <h3 className="text-base font-bold text-foreground">Release-readiness questions</h3>
              <p className="mt-1 text-sm text-muted-foreground">
                Practical boundaries that keep the verdict understandable instead of turning it into a black box.
              </p>
            </div>
            <div className="mt-4 grid grid-cols-1 gap-4 sm:grid-cols-2">
              {releaseFaq.map((entry) => (
                <article key={entry.question}>
                  <h3 className="text-sm font-bold text-foreground">{entry.question}</h3>
                  <p className="mt-1 text-sm text-muted-foreground">{entry.answer}</p>
                </article>
              ))}
            </div>
          </div>
        </section>

        <section className="border-b border-border py-16" id="glossary" aria-labelledby="glossary-heading">
          <div className="mx-auto max-w-6xl px-6">
            <div className="flex max-w-2xl flex-col gap-2">
              <p className="text-sm font-medium text-primary">Glossary</p>
              <h2 id="glossary-heading" className="text-2xl font-bold text-foreground sm:text-3xl">
                The hardware-release terms behind the verdict.
              </h2>
              <p className="text-sm text-muted-foreground">
                These definitions describe the evidence BoardReadyOps reports. For implementation details, continue to
                the canonical documentation; for the public machine-readable service contract, see OpenAPI.
              </p>
            </div>
            <dl className="mt-8 grid grid-cols-1 gap-6 sm:grid-cols-2">
              {glossaryTerms.map((entry) => (
                <div key={entry.term}>
                  <dt className="text-sm font-bold text-foreground">{entry.term}</dt>
                  <dd className="mt-1 text-sm text-muted-foreground">{entry.definition}</dd>
                </div>
              ))}
            </dl>
            <nav className="mt-8 flex flex-wrap gap-4 text-sm" aria-label="Technical discovery references">
              <a href="https://docs.boardreadyops.com" className="text-primary hover:underline">
                Read the documentation
              </a>
              <a href="/openapi.json" className="text-primary hover:underline">
                OpenAPI
              </a>
              <a href="/llms.txt" className="text-primary hover:underline">
                LLM discovery
              </a>
              <a href="/sitemap.md" className="text-primary hover:underline">
                Markdown sitemap
              </a>
            </nav>
          </div>
        </section>

        <section className="border-b border-border bg-muted py-16" aria-labelledby="landing-cta-heading">
          <div className="mx-auto flex max-w-6xl flex-col gap-6 px-6 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <p className="text-sm font-medium text-primary">Next release</p>
              <h2 id="landing-cta-heading" className="text-2xl font-bold text-foreground sm:text-3xl">
                Check your next board before you order it.
              </h2>
            </div>
            <div className="flex flex-wrap items-center gap-3">
              <a className={`${buttonVariants({ variant: "default", size: "lg" })} gap-2`} href={installUrl}>
                <span>Install on GitHub</span>
                <span aria-hidden="true">↗</span>
              </a>
              <Link className={buttonVariants({ variant: "secondary", size: "lg" })} href="/setup">
                Review setup first
              </Link>
            </div>
          </div>
        </section>
      </main>

      <footer className="py-10">
        <div className="mx-auto flex max-w-6xl flex-col items-center gap-3 px-6 text-center sm:flex-row sm:justify-between sm:text-left">
          <span className="flex items-center gap-2 text-sm font-bold text-foreground">
            <BrandMarkIcon size={20} />
            BoardReadyOps
          </span>
          <p className="text-sm text-muted-foreground">
            Release readiness checks for hardware teams. Your repository and its full workflow logs stay the source of
            truth.
          </p>
          <a href="https://docs.boardreadyops.com" className="text-sm text-primary hover:underline">
            Documentation
          </a>
        </div>
      </footer>
    </div>
  );
}
