export const cloudDatabaseSchemaVersion = 48;

export const cloudDatabaseModels = [
  "Installation",
  "Repository",
  "RepositorySetupRevision",
  "RepositorySetupProbe",
  "ReleaseRun",
  "Finding",
  "Artifact",
  "ArtifactDeletionJob",
  "Board",
  "BoardBomSnapshot",
  "BoardBomComponent",
  "BoardSupplyWatch",
  "BoardSupplyFinding",
  "ComponentLifecycleObservation",
  "RunnerRegistration",
  "RunnerRegistrationEnrollment",
  "RunnerExecutionPolicy",
  "ManagedRunnerIdentity",
  "RunnerJobLease",
  "RunnerRequestNonce",
  "RunnerArtifactUploadCapability",
  "AuditEvent",
  "ReleaseRunResult",
  "ReleaseRunAttempt",
  "ReleaseRunTransitionEvent",
  "WebhookInbox",
  "ControlPlaneJob",
  "ControlPlaneOutbox",
  "ControlPlaneReconciliationItem",
  "ControlPlaneReplayOperation",
  "Review",
  "ReviewRevision",
  "FindingDecision",
  "FindingAssignment",
  "ReviewComment",
  "ReviewApproval",
  "UploadManifest",
  "VisualSnapshot",
  "ExternalReviewLink",
] as const;

export type CloudDatabaseModel = (typeof cloudDatabaseModels)[number];

export * from "./review-store.js";
