// biome-ignore-all lint/suspicious/noTemplateCurlyInString: Workflow expressions are literal YAML template data.
/** Canonical target-runner workflow bytes.
 *
 * Generated from .github/workflows/readiness-runner.yml; the contract test
 * enforces exact equality after substituting the validated cloud origin.
 * Never weaken OIDC result URL, SHA, runner environment, attempt, or safe-mode
 * checks in the setup PR generator.
 */
export const defaultReadinessWorkflowTemplate = [
  "name: BoardReadyOps Readiness Runner\n",
  "\n",
  "on:\n",
  "  workflow_dispatch:\n",
  "    inputs:\n",
  "      run_id:\n",
  "        required: true\n",
  "        type: string\n",
  "      execution_attempt_id:\n",
  "        required: true\n",
  "        type: string\n",
  "      target:\n",
  "        required: true\n",
  "        type: string\n",
  "      head_sha:\n",
  "        required: true\n",
  "        type: string\n",
  "      result_url:\n",
  "        required: true\n",
  "        type: string\n",
  "      safe_mode:\n",
  "        required: false\n",
  "        type: string\n",
  '        default: "false"\n',
  "      safe_mode_reasons:\n",
  "        required: false\n",
  "        type: string\n",
  '        default: ""\n',
  "      setup_probe_id:\n",
  "        required: false\n",
  "        type: string\n",
  '        default: ""\n',
  "      setup_result_url:\n",
  "        required: false\n",
  "        type: string\n",
  '        default: ""\n',
  "\n",
  "permissions:\n",
  "  contents: read\n",
  "\n",
  "concurrency:\n",
  "  group: boardreadyops-cloud-${{ inputs.run_id }}\n",
  "  cancel-in-progress: false\n",
  "\n",
  "jobs:\n",
  "  readiness:\n",
  "    if: ${{ inputs.setup_probe_id == '' }}\n",
  "    permissions:\n",
  "      actions: read\n",
  "      checks: read\n",
  "      contents: read\n",
  "      id-token: write\n",
  "    runs-on: ubuntu-latest\n",
  "    timeout-minutes: 30\n",
  "    steps:\n",
  "      - name: Validate dispatch binding\n",
  "        id: validate\n",
  "        env:\n",
  "          RUN_ID: ${{ inputs.run_id }}\n",
  "          EXECUTION_ATTEMPT_ID: ${{ inputs.execution_attempt_id }}\n",
  "          TARGET: ${{ inputs.target }}\n",
  "          HEAD_SHA: ${{ inputs.head_sha }}\n",
  "          RESULT_URL: ${{ inputs.result_url }}\n",
  "          CLOUD_ORIGIN: ${{ vars.BOARDREADYOPS_CLOUD_ORIGIN }}\n",
  "          SAFE_MODE: ${{ inputs.safe_mode }}\n",
  "          SAFE_MODE_REASONS: ${{ inputs.safe_mode_reasons }}\n",
  "        run: |\n",
  '          if ! [[ "$RUN_ID" =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$ ]]; then\n',
  '            echo "run_id must be a lowercase UUID" >&2\n',
  "            exit 1\n",
  "          fi\n",
  '          if ! [[ "$EXECUTION_ATTEMPT_ID" =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$ ]]; then\n',
  '            echo "execution_attempt_id must be a lowercase UUID" >&2\n',
  "            exit 1\n",
  "          fi\n",
  '          if [ "$TARGET" != "$GITHUB_REPOSITORY" ]; then\n',
  '            echo "target must match the repository that owns this workflow" >&2\n',
  "            exit 1\n",
  "          fi\n",
  '          if ! [[ "$HEAD_SHA" =~ ^[0-9a-f]{40}$ ]]; then\n',
  '            echo "head_sha must be a full lowercase commit SHA" >&2\n',
  "            exit 1\n",
  "          fi\n",
  "\n",
  '          if ! [[ "$CLOUD_ORIGIN" =~ ^https://[A-Za-z0-9.-]+(:[0-9]+)?$ ]]; then\n',
  '            echo "BOARDREADYOPS_CLOUD_ORIGIN must be an HTTPS origin" >&2\n',
  "            exit 1\n",
  "          fi\n",
  '          expected_url="${CLOUD_ORIGIN}/api/v1/runs/github-actions-result?run_id=${RUN_ID}&attempt_id=${EXECUTION_ATTEMPT_ID}"\n',
  '          if [ "$RESULT_URL" != "$expected_url" ]; then\n',
  '            echo "result_url must target the BoardReadyOps GitHub Actions callback for this run" >&2\n',
  "            exit 1\n",
  "          fi\n",
  "\n",
  '          case "$SAFE_MODE" in\n',
  "            true|false) ;;\n",
  "            *)\n",
  '              echo "safe_mode must be true or false" >&2\n',
  "              exit 1\n",
  "              ;;\n",
  "          esac\n",
  '          if [ "$SAFE_MODE" = "false" ] && [ -n "$SAFE_MODE_REASONS" ]; then\n',
  '            echo "safe_mode_reasons requires safe_mode=true" >&2\n',
  "            exit 1\n",
  "          fi\n",
  '          if [ "$SAFE_MODE" = "true" ]; then\n',
  '            if [ -z "$SAFE_MODE_REASONS" ]; then\n',
  '              echo "safe_mode=true requires at least one reason" >&2\n',
  "              exit 1\n",
  "            fi\n",
  "            declare -A seen_reasons=()\n",
  "            IFS=',' read -r -a reasons <<< \"$SAFE_MODE_REASONS\"\n",
  '            for reason in "${reasons[@]}"; do\n',
  '              case "$reason" in\n',
  "                draft-pull-request|fork-pull-request|private-repository) ;;\n",
  "                *)\n",
  '                  echo "unsupported safe-mode reason: $reason" >&2\n',
  "                  exit 1\n",
  "                  ;;\n",
  "              esac\n",
  '              if [ -n "${seen_reasons[$reason]:-}" ]; then\n',
  '                echo "duplicate safe-mode reason: $reason" >&2\n',
  "                exit 1\n",
  "              fi\n",
  "              seen_reasons[$reason]=1\n",
  "            done\n",
  "          fi\n",
  "\n",
  "      - name: Check out exact target commit\n",
  "        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0\n",
  "        with:\n",
  "          ref: ${{ inputs.head_sha }}\n",
  "          persist-credentials: false\n",
  "\n",
  "      - name: Verify exact target commit\n",
  "        env:\n",
  "          HEAD_SHA: ${{ inputs.head_sha }}\n",
  "        run: |\n",
  '          actual_sha="$(git rev-parse HEAD)"\n',
  '          if [ "$actual_sha" != "$HEAD_SHA" ]; then\n',
  '            echo "checkout SHA mismatch: expected $HEAD_SHA, got $actual_sha" >&2\n',
  "            exit 1\n",
  "          fi\n",
  "\n",
  "      - name: Install KiCad 10\n",
  "        run: |\n",
  "          sudo add-apt-repository --yes ppa:kicad/kicad-10.0-releases\n",
  "          sudo apt-get update -qq\n",
  "          sudo apt-get install --yes kicad\n",
  '          version="$(kicad-cli version)"\n',
  '          case "$version" in\n',
  "            10.0.*) ;;\n",
  "            *)\n",
  '              echo "Expected KiCad 10.0.*, got $version" >&2\n',
  "              exit 1\n",
  "              ;;\n",
  "          esac\n",
  "\n",
  "      - name: Run BoardReadyOps\n",
  "        id: readiness\n",
  "        continue-on-error: true\n",
  "        env:\n",
  "          GITHUB_TOKEN: ${{ github.token }}\n",
  "          BOARDREADYOPS_PR_HEAD_SHA: ${{ inputs.head_sha }}\n",
  "          BOARDREADYOPS_CLOUD_RUN_ID: ${{ inputs.run_id }}\n",
  "        uses: oaslananka/boardreadyops@6d3b721c3f8307a517d360b28f4d50b824d81278 # v1.24.1\n",
  "        with:\n",
  "          project: ${{ vars.BOARDREADYOPS_PROJECT || '' }}\n",
  "          config: ${{ vars.BOARDREADYOPS_CONFIG || 'boardreadyops.yml' }}\n",
  "          safe-mode: ${{ inputs.safe_mode }}\n",
  "          mode: enforce\n",
  '          require-kicad: "true"\n',
  "          fail-on: high\n",
  "          sarif: boardreadyops.sarif.json\n",
  "          json: boardreadyops.findings.json\n",
  "          markdown: boardreadyops.report.md\n",
  '          upload-sarif: "false"\n',
  '          upload-artifacts: "true"\n',
  '          comment-pr: "false"\n',
  "\n",
  "      - name: Publish OIDC-authenticated cloud result\n",
  "        if: always() && steps.validate.outcome == 'success'\n",
  "        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0\n",
  "        env:\n",
  "          RUN_ID: ${{ inputs.run_id }}\n",
  "          EXECUTION_ATTEMPT_ID: ${{ inputs.execution_attempt_id }}\n",
  "          HEAD_SHA: ${{ inputs.head_sha }}\n",
  "          RESULT_URL: ${{ inputs.result_url }}\n",
  "          READINESS_OUTCOME: ${{ steps.readiness.outcome }}\n",
  "          SAFE_MODE: ${{ inputs.safe_mode }}\n",
  "          SAFE_MODE_REASONS: ${{ inputs.safe_mode_reasons }}\n",
  "        with:\n",
  "          script: |\n",
  '            const fs = require("node:fs");\n',
  "            const runId = process.env.RUN_ID;\n",
  "            const executionAttemptId = process.env.EXECUTION_ATTEMPT_ID;\n",
  "            const targetSha = process.env.HEAD_SHA;\n",
  "            const resultUrl = process.env.RESULT_URL;\n",
  "            const readinessOutcome = process.env.READINESS_OUTCOME;\n",
  '            const trustMode = process.env.SAFE_MODE === "true" ? "safe" : "standard";\n',
  '            const safeModeReasons = process.env.SAFE_MODE_REASONS ?? "";\n',
  '            const reportPath = "boardreadyops.findings.json";\n',
  "\n",
  "            let report;\n",
  "            try {\n",
  '              report = JSON.parse(fs.readFileSync(reportPath, "utf8"));\n',
  "            } catch {\n",
  "              report = undefined;\n",
  "            }\n",
  "\n",
  "            const reportAvailable =\n",
  "              report?.schemaVersion === 1 &&\n",
  '              typeof report.summary === "object" &&\n',
  "              report.summary !== null &&\n",
  "              Array.isArray(report.findings);\n",
  "            const policyFailed = reportAvailable && report.summary.failed === true;\n",
  '            const operationalFailure = !reportAvailable || (readinessOutcome !== "success" && !policyFailed);\n',
  "            const hardwareImpact =\n",
  '              reportAvailable && report.hardwareImpact && typeof report.hardwareImpact === "object"\n',
  "                ? report.hardwareImpact\n",
  "                : undefined;\n",
  "            const rawFindings = reportAvailable ? report.findings : [];\n",
  '            const severity = (value) => value === "critical" ? "error" :\n',
  '              ["error", "high", "medium", "low", "info"].includes(value) ? value : "error";\n',
  "            const boundedText = (value, fallback, maximum) => {\n",
  "              const normalized = String(value ?? fallback).trim() || fallback;\n",
  "              return normalized.slice(0, maximum);\n",
  "            };\n",
  "            const finiteMetric = (value, fallback = 0) => {\n",
  "              const numeric = Number(value);\n",
  "              return Number.isFinite(numeric) ? numeric : fallback;\n",
  "            };\n",
  "            const findings = rawFindings.slice(0, 500).map((finding) => ({\n",
  '              ruleId: boundedText(finding.ruleId, "boardreadyops.unknown", 256),\n',
  "              severity: severity(finding.severity),\n",
  '              message: boundedText(finding.message, "BoardReadyOps reported an unspecified finding.", 4000),\n',
  '              ...(typeof finding.resource?.path === "string" && finding.resource.path.trim().length > 0\n',
  '                ? { path: boundedText(finding.resource.path, "unknown", 1024) }\n',
  "                : {}),\n",
  "            }));\n",
  "            const rawBoms = reportAvailable && Array.isArray(report.boms) ? report.boms : [];\n",
  "            const componentText = (value, maximum) => {\n",
  '              const normalized = String(value ?? "").trim();\n',
  "              return normalized.length > 0 ? normalized.slice(0, maximum) : undefined;\n",
  "            };\n",
  "            const positiveCount = (value) => {\n",
  "              const numeric = Number(value);\n",
  "              return Number.isSafeInteger(numeric) && numeric > 0 && numeric <= 1000000 ? numeric : undefined;\n",
  "            };\n",
  "            const releaseMode = (value) =>\n",
  '              value === "prototype" || value === "pilot" || value === "production" ? value : undefined;\n',
  "            const defined = (entries) => Object.fromEntries(entries.filter(([, value]) => value !== undefined));\n",
  "            const boms = rawBoms\n",
  '              .filter((bom) => typeof bom?.project === "string" && Array.isArray(bom.components))\n',
  "              .slice(0, 50)\n",
  "              .map((bom) => {\n",
  "                const parsedReleaseMode = releaseMode(bom.releaseMode);\n",
  "                return {\n",
  '                  project: boundedText(bom.project, "unknown.kicad_pro", 1024),\n',
  "                  ...(parsedReleaseMode ? { releaseMode: parsedReleaseMode } : {}),\n",
  "                  components: bom.components\n",
  "                    .filter((component) => componentText(component?.reference, 64) !== undefined)\n",
  "                    .slice(0, 5000)\n",
  "                    .map((component) =>\n",
  "                      defined([\n",
  '                        ["reference", componentText(component.reference, 64)],\n',
  '                        ["mpn", componentText(component.mpn, 128)],\n',
  '                        ["manufacturer", componentText(component.manufacturer, 128)],\n',
  '                        ["value", componentText(component.value, 256)],\n',
  '                        ["footprint", componentText(component.footprint, 256)],\n',
  '                        ["quantity", positiveCount(component.quantity)],\n',
  '                        ["dnp", typeof component.dnp === "boolean" ? component.dnp : undefined],\n',
  '                        ["lifecycle", componentText(component.lifecycle, 64)],\n',
  "                        [\n",
  '                          "identityKey",\n',
  '                          /^[0-9a-f]{16}$/.test(String(component.identityKey ?? ""))\n',
  "                            ? String(component.identityKey)\n",
  "                            : undefined,\n",
  "                        ],\n",
  "                      ]),\n",
  "                    ),\n",
  "                };\n",
  "              });\n",
  "            const summary = reportAvailable ? report.summary : {};\n",
  "            const actionsRunUrl =\n",
  "              `${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}`;\n",
  '            const reportLinks = actionsRunUrl.startsWith("https://")\n',
  '              ? [{ label: "GitHub Actions run", url: actionsRunUrl.slice(0, 2048) }]\n',
  "              : [];\n",
  "            const payload = {\n",
  "              version: 1,\n",
  "              executionAttemptId,\n",
  '              status: operationalFailure ? "failed" : "completed",\n',
  '              conclusion: operationalFailure || policyFailed ? "failure" : "success",\n',
  '              decision: operationalFailure ? "error" : policyFailed ? "fail" : "pass",\n',
  "              findings,\n",
  "              artifacts: [],\n",
  "              metrics: {\n",
  "                findings_total: finiteMetric(summary.total, findings.length),\n",
  "                findings_critical: finiteMetric(summary.critical),\n",
  "                findings_high: finiteMetric(summary.high),\n",
  "                findings_medium: finiteMetric(summary.medium),\n",
  "                findings_low: finiteMetric(summary.low),\n",
  "                findings_info: finiteMetric(summary.info),\n",
  "              },\n",
  "              reportLinks,\n",
  "              ...(hardwareImpact ? { hardwareImpact } : {}),\n",
  "              ...(boms.length > 0 ? { boms } : {}),\n",
  "            };\n",
  '            const payloadTooLarge = () => Buffer.byteLength(JSON.stringify(payload), "utf8") > 900 * 1024;\n',
  "            // Bound the transmitted component count before measuring. The contract permits\n",
  "            // 50 boards of 5000 components, which serialises far past the transmit budget;\n",
  "            // trimming up front keeps the size checks below to a few dozen serialisations\n",
  "            // instead of one per dropped component.\n",
  "            let componentBudget = 20000;\n",
  "            for (const bom of boms) {\n",
  "              if (bom.components.length > componentBudget) bom.components = bom.components.slice(0, componentBudget);\n",
  "              componentBudget -= bom.components.length;\n",
  "            }\n",
  "            // Shed BOM rows before findings: a finding is a decision input for this release,\n",
  "            // while a BOM row is supplementary evidence that the next run re-reports. Whole\n",
  "            // boards are dropped so this terminates in at most one pass per board.\n",
  "            while (payloadTooLarge() && boms.length > 0) {\n",
  "              boms.pop();\n",
  "            }\n",
  "            if (boms.length === 0) delete payload.boms;\n",
  "            while (payloadTooLarge() && findings.length > 0) {\n",
  "              findings.pop();\n",
  "            }\n",
  "            payload.metrics.findings_transmitted = findings.length;\n",
  "            payload.metrics.boms_transmitted = boms.length;\n",
  "\n",
  '            const audience = `boardreadyops-cloud:${runId}:${executionAttemptId}:${targetSha}:${trustMode}:${safeModeReasons || "none"}`;\n',
  "            const oidcToken = await core.getIDToken(audience);\n",
  "            let response;\n",
  "            for (let attempt = 1; attempt <= 3; attempt += 1) {\n",
  "              response = await fetch(resultUrl, {\n",
  '                method: "POST",\n',
  "                headers: {\n",
  "                  authorization: `Bearer ${oidcToken}`,\n",
  '                  "content-type": "application/json",\n',
  '                  "x-boardreadyops-trust-mode": trustMode,\n',
  '                  "x-boardreadyops-safe-mode-reasons": safeModeReasons,\n',
  "                },\n",
  "                body: JSON.stringify(payload),\n",
  "              });\n",
  "              if (response.ok) break;\n",
  "              if (attempt < 3) await new Promise((resolve) => setTimeout(resolve, attempt * 1000));\n",
  "            }\n",
  "            if (!response?.ok) {\n",
  '              const responseText = response ? (await response.text()).slice(0, 512) : "no response";\n',
  '              throw new Error(`BoardReadyOps Cloud callback failed: HTTP ${response?.status ?? "unknown"}: ${responseText}`);\n',
  "            }\n",
  "            if (operationalFailure || policyFailed) {\n",
  '              core.setFailed(policyFailed ? "BoardReadyOps found blocking readiness findings." : "BoardReadyOps execution failed or did not produce a valid report.");\n',
  "            }\n",
  "\n",
  "  setup-probe:\n",
  "    if: ${{ inputs.setup_probe_id != '' }}\n",
  "    permissions:\n",
  "      contents: read\n",
  "      id-token: write\n",
  "    runs-on: ubuntu-latest\n",
  "    timeout-minutes: 10\n",
  "    steps:\n",
  "      - name: Validate setup probe binding\n",
  "        id: validate\n",
  "        env:\n",
  "          SETUP_PROBE_ID: ${{ inputs.setup_probe_id }}\n",
  "          SETUP_RESULT_URL: ${{ inputs.setup_result_url }}\n",
  "          TARGET: ${{ inputs.target }}\n",
  "          CLOUD_ORIGIN: ${{ vars.BOARDREADYOPS_CLOUD_ORIGIN }}\n",
  "        run: |\n",
  '          if ! [[ "$SETUP_PROBE_ID" =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$ ]]; then\n',
  '            echo "setup_probe_id must be a lowercase UUID" >&2\n',
  "            exit 1\n",
  "          fi\n",
  '          if [ "$TARGET" != "$GITHUB_REPOSITORY" ]; then\n',
  '            echo "target must match the repository that owns this workflow" >&2\n',
  "            exit 1\n",
  "          fi\n",
  '          if ! [[ "$CLOUD_ORIGIN" =~ ^https://[A-Za-z0-9.-]+(:[0-9]+)?$ ]]; then\n',
  '            echo "BOARDREADYOPS_CLOUD_ORIGIN must be an HTTPS origin" >&2\n',
  "            exit 1\n",
  "          fi\n",
  '          expected_url="${CLOUD_ORIGIN}/api/v1/setup-probes/result?probe_id=${SETUP_PROBE_ID}"\n',
  '          if [ "$SETUP_RESULT_URL" != "$expected_url" ]; then\n',
  '            echo "setup_result_url must target the BoardReadyOps setup callback for this probe" >&2\n',
  "            exit 1\n",
  "          fi\n",
  "\n",
  "      - name: Check out default branch\n",
  "        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0\n",
  "        with:\n",
  "          persist-credentials: false\n",
  "\n",
  "      - name: Check out verified BoardReadyOps release\n",
  "        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0\n",
  "        with:\n",
  "          repository: oaslananka/boardreadyops\n",
  "          ref: ce925376bd71daf7e07f31fb1bb19a8bde30b172 # v1.24.1\n",
  "          path: .boardreadyops-tool\n",
  "          persist-credentials: false\n",
  "          sparse-checkout: |\n",
  "            dist/cli/index.cjs\n",
  "            package.json\n",
  "          sparse-checkout-cone-mode: false\n",
  "\n",
  "      - name: Validate BoardReadyOps configuration\n",
  "        id: inspect\n",
  "        env:\n",
  "          BOARDREADYOPS_LOCALE: en\n",
  "          CONFIG_PATH: ${{ vars.BOARDREADYOPS_CONFIG || 'boardreadyops.yml' }}\n",
  "        run: |\n",
  '          observed_sha="$(git -C "$GITHUB_WORKSPACE" rev-parse HEAD)"\n',
  '          if ! [[ "$observed_sha" =~ ^[0-9a-f]{40}$ ]]; then\n',
  '            echo "default-branch checkout did not resolve to a full commit SHA" >&2\n',
  "            exit 1\n",
  "          fi\n",
  "\n",
  '          tool_version="$(node "$GITHUB_WORKSPACE/.boardreadyops-tool/dist/cli/index.cjs" --version)"\n',
  '          if [ "$tool_version" != "1.24.1" ]; then\n',
  '            echo "verified BoardReadyOps checkout returned unexpected version: $tool_version" >&2\n',
  "            exit 1\n",
  "          fi\n",
  "\n",
  '          OBSERVED_SHA="$observed_sha" TOOL_VERSION="$tool_version" node <<\'NODE\'\n',
  '          const fs = require("node:fs");\n',
  '          const path = require("node:path");\n',
  '          const { execFileSync } = require("node:child_process");\n',
  "\n",
  "          const workspace = fs.realpathSync(process.env.GITHUB_WORKSPACE);\n",
  '          const configured = String(process.env.CONFIG_PATH ?? "").trim();\n',
  "          const observedSha = process.env.OBSERVED_SHA;\n",
  "          const toolVersion = process.env.TOOL_VERSION;\n",
  "          if (!configured || path.isAbsolute(configured)) {\n",
  '            throw new Error("CONFIG_PATH must stay within the checked-out repository");\n',
  "          }\n",
  "\n",
  "          const candidate = path.resolve(workspace, configured);\n",
  "          const relative = path.relative(workspace, candidate);\n",
  '          if (relative === ".." || relative.startsWith(`..${path.sep}`) || path.isAbsolute(relative)) {\n',
  '            throw new Error("CONFIG_PATH must stay within the checked-out repository");\n',
  "          }\n",
  "\n",
  "          let tracked = true;\n",
  "          try {\n",
  '            execFileSync("git", ["-C", workspace, "ls-files", "--error-unmatch", "--", configured], {\n',
  '              stdio: "ignore",\n',
  "            });\n",
  "          } catch {\n",
  "            tracked = false;\n",
  "          }\n",
  "          if (!tracked || !fs.existsSync(candidate)) {\n",
  '            fs.writeFileSync("setup-result.json", JSON.stringify({\n',
  "              contractVersion: 1,\n",
  '              configStatus: "missing",\n',
  "              observedSha,\n",
  "              toolVersion,\n",
  '              diagnostics: ["The configured BoardReadyOps path is missing on the default branch."],\n',
  "            }));\n",
  "            process.exit(0);\n",
  "          }\n",
  "\n",
  "          const metadata = fs.lstatSync(candidate);\n",
  "          const realCandidate = fs.realpathSync(candidate);\n",
  "          const realRelative = path.relative(workspace, realCandidate);\n",
  "          if (\n",
  "            metadata.isSymbolicLink() ||\n",
  "            !metadata.isFile() ||\n",
  '            realRelative === ".." ||\n',
  "            realRelative.startsWith(`..${path.sep}`) ||\n",
  "            path.isAbsolute(realRelative)\n",
  "          ) {\n",
  '            throw new Error("CONFIG_PATH must resolve to a tracked regular file inside the checked-out repository");\n',
  "          }\n",
  "\n",
  '          const probeRoot = path.join(process.env.RUNNER_TEMP, "boardreadyops-setup-probe");\n',
  "          fs.rmSync(probeRoot, { recursive: true, force: true });\n",
  "          fs.mkdirSync(probeRoot, { recursive: true });\n",
  '          fs.copyFileSync(realCandidate, path.join(probeRoot, "boardreadyops.yml"));\n',
  "          NODE\n",
  "\n",
  "          if [ -f setup-result.json ]; then\n",
  "            exit 0\n",
  "          fi\n",
  "\n",
  "          (\n",
  '            cd "$RUNNER_TEMP/boardreadyops-setup-probe"\n',
  '            node "$GITHUB_WORKSPACE/.boardreadyops-tool/dist/cli/index.cjs" doctor --check repository --format json > "$GITHUB_WORKSPACE/doctor.json"\n',
  "          )\n",
  '          OBSERVED_SHA="$observed_sha" TOOL_VERSION="$tool_version" node <<\'NODE\'\n',
  '          const fs = require("node:fs");\n',
  '          const report = JSON.parse(fs.readFileSync("doctor.json", "utf8"));\n',
  '          const reportToolVersion = String(report?.tool?.version ?? "").trim();\n',
  "          if (reportToolVersion !== process.env.TOOL_VERSION) {\n",
  '            throw new Error("BoardReadyOps doctor reported an unexpected tool version");\n',
  "          }\n",
  '          const repository = report?.checks?.find((check) => check?.name === "repository");\n',
  "          const configItem = repository?.items?.find((item) =>\n",
  '            typeof item?.message === "string" &&\n',
  '            (item.message.includes("found and valid") || item.message.includes("configuration is invalid"))\n',
  "          );\n",
  '          const configStatus = configItem?.severity === "pass" ? "ready" : "invalid";\n',
  '          const diagnostics = configStatus === "ready"\n',
  "            ? []\n",
  '            : [String(configItem?.message ?? "BoardReadyOps could not validate the configuration.").slice(0, 512)];\n',
  '          fs.writeFileSync("setup-result.json", JSON.stringify({\n',
  "            contractVersion: 1,\n",
  "            configStatus,\n",
  '            configVersion: configStatus === "ready" ? 1 : undefined,\n',
  "            observedSha: process.env.OBSERVED_SHA,\n",
  "            toolVersion: reportToolVersion,\n",
  "            diagnostics,\n",
  "          }));\n",
  "          NODE\n",
  "\n",
  "      - name: Publish OIDC-authenticated setup result\n",
  "        if: always() && steps.validate.outcome == 'success' && steps.inspect.outcome == 'success'\n",
  "        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0\n",
  "        env:\n",
  "          SETUP_PROBE_ID: ${{ inputs.setup_probe_id }}\n",
  "          SETUP_RESULT_URL: ${{ inputs.setup_result_url }}\n",
  "        with:\n",
  "          script: |\n",
  '            const fs = require("node:fs");\n',
  "            const probeId = process.env.SETUP_PROBE_ID;\n",
  "            const resultUrl = process.env.SETUP_RESULT_URL;\n",
  '            const payload = JSON.parse(fs.readFileSync("setup-result.json", "utf8"));\n',
  "            const oidcToken = await core.getIDToken(`boardreadyops-setup:${probeId}`);\n",
  "            let response;\n",
  "            for (let attempt = 1; attempt <= 3; attempt += 1) {\n",
  "              response = await fetch(resultUrl, {\n",
  '                method: "POST",\n',
  "                headers: {\n",
  "                  authorization: `Bearer ${oidcToken}`,\n",
  '                  "content-type": "application/json",\n',
  "                },\n",
  "                body: JSON.stringify(payload),\n",
  "              });\n",
  "              if (response.ok) break;\n",
  "              if (attempt < 3) await new Promise((resolve) => setTimeout(resolve, attempt * 1000));\n",
  "            }\n",
  "            if (!response?.ok) {\n",
  '              const responseText = response ? (await response.text()).slice(0, 512) : "no response";\n',
  '              throw new Error(`BoardReadyOps setup callback failed: HTTP ${response?.status ?? "unknown"}: ${responseText}`);\n',
  "            }\n",
].join("");
