export interface AltiumHeadlessOptions {
  projectPath: string;
  outputDirectory: string;
  includeIpc2581?: boolean | undefined;
  includeStepModel?: boolean | undefined;
}

export interface CadenceSkillOptions {
  boardPath: string;
  outputDirectory: string;
  paramFile?: string | undefined;
}

export interface NativeCadBatchResult {
  engine: "altium" | "cadence_allegro";
  executableName: string;
  commandLine: string;
  scriptFileName: string;
  scriptContent: string;
}

/**
 * Generates an Altium Designer DelphiScript automation file (.pas) for headless batch export.
 * Executable invocation: DXP.EXE -RRunScript -D<projectPath>
 */
export function generateAltiumHeadlessScript(options: AltiumHeadlessOptions): string {
  const normProj = options.projectPath.replace(/\\/g, "/");
  const normOut = options.outputDirectory.replace(/\\/g, "/");
  const ipcCall = options.includeIpc2581 ? "    GenerateIPC2581(Project, OutDir + '/board.xml');\n" : "";

  return `// BoardReadyOps Native Altium Designer Headless Export Script
// Auto-generated by BoardReadyOps Enterprise Runner Agent

Procedure RunHeadlessExport;
Var
    Workspace : IWorkspace;
    Project   : IProject;
    OutDir    : String;
Begin
    OutDir := '${normOut}';
    Workspace := GetWorkspace;
    If Workspace = Nil Then Exit;

    Project := Workspace.DM_OpenProject('${normProj}', True);
    If Project = Nil Then Exit;

    // 1. Export Gerber RS-274X and NC Drill
    GenerateGerbers(Project, OutDir);
    GenerateNCDrill(Project, OutDir);

    // 2. Export Pick and Place (Centroid)
    GeneratePickAndPlace(Project, OutDir + '/pick_and_place.csv');

    // 3. Export Bill of Materials (BOM)
    GenerateBOM(Project, OutDir + '/bom.csv');
${ipcCall}
    Project.DM_Save;
End;
`;
}

/**
 * Generates a Cadence Allegro SKILL automation script (.il) for headless batch export.
 * Executable invocation: allegro -nographics -replay <scriptFile>
 */
export function generateCadenceSkillScript(options: CadenceSkillOptions): string {
  const normBoard = options.boardPath.replace(/\\/g, "/");
  const normOut = options.outputDirectory.replace(/\\/g, "/");

  return `; BoardReadyOps Native Cadence Allegro SKILL Headless Export Script
; Auto-generated by BoardReadyOps Enterprise Runner Agent

procedure(RunBoardReadyOpsExport()
  let((boardFile outDir)
    boardFile = "${normBoard}"
    outDir = "${normOut}"

    ; 1. Open Database
    axlOpenDesignForBatch(boardFile "r")

    ; 2. Generate Artwork (Gerber RS-274X)
    axlRunBatchDBDoctor()
    axlArtworkRun(outDir)

    ; 3. Generate NC Drill
    axlNCParameters(list("units" "metric" "format" "5.3"))
    axlNCDrillRun(outDir)

    ; 4. Export Component Placement & Centroids
    axlExtractToFile(strcat(outDir "/components.csv") list("REFDES" "COMP_DEVICE_TYPE" "SYM_X" "SYM_Y" "SYM_ROTATE" "LAYER"))

    ; 5. Close Design
    axlCloseDesign(nil)
    exit(0)
  )
)
RunBoardReadyOpsExport()
`;
}

/**
 * Builds the batch command and script bundle required to execute native CAD exports
 * inside an enterprise worker or customer-hosted CAD machine.
 */
export function buildNativeCadBatchCommand(
  engine: "altium" | "cadence_allegro",
  designPath: string,
  outputDir: string,
): NativeCadBatchResult {
  if (engine === "altium") {
    const scriptFileName = "export_altium.pas";
    const scriptContent = generateAltiumHeadlessScript({
      projectPath: designPath,
      outputDirectory: outputDir,
      includeIpc2581: true,
    });
    return {
      engine: "altium",
      executableName: "DXP.EXE",
      commandLine: `DXP.EXE -RRunScript -D"${designPath}" "${scriptFileName}"`,
      scriptFileName,
      scriptContent,
    };
  }

  const scriptFileName = "export_allegro.il";
  const scriptContent = generateCadenceSkillScript({
    boardPath: designPath,
    outputDirectory: outputDir,
  });
  return {
    engine: "cadence_allegro",
    executableName: "allegro",
    commandLine: `allegro -nographics -replay "${scriptFileName}"`,
    scriptFileName,
    scriptContent,
  };
}
