/**
 * Route inventory for the BoardReadyOps QA audit.
 *
 * Generated by hand from `apps/web/app/**\/page.tsx`, not scanned at runtime, because the
 * audit needs to know per-route auth/DB requirements and safe fixture ids that only a human
 * (or an agent reading the route source) can supply — a directory walk alone can't tell you
 * that `/repositories/[repositoryId]` 404s without both a session and DATABASE_URL, or which
 * ids are demo-safe.
 *
 * `tests/unit/web/*.test.ts` already covers component-level rendering for every route below;
 * this inventory exists for the black-box, server-rendered, real-browser audit in
 * `tests/e2e/qa-audit.spec.ts` — a different failure class (hydration, console errors, axe
 * violations against actual computed styles, real navigation).
 *
 * When a new `page.tsx` is added under `apps/web/app`, add it here too.
 * `tests/e2e/route-inventory-coverage.spec.ts` fails the build if the two drift apart.
 */

export type RouteAuth = "public" | "authenticated";

export type QaRoute = {
  /** Stable id used in reports and `--grep` filters. */
  id: string;
  /** Path to request, with `:param` placeholders already substituted. */
  path: string;
  /** Human label for reports. */
  label: string;
  auth: RouteAuth;
  /** True if the route's real content requires DATABASE_URL (no demo/fixture fallback). */
  requiresDb: boolean;
  /** Skip this route's dynamic content entirely without DATABASE_URL, rather than auditing a stub. */
  skipWithoutDb?: boolean;
  /** Extra internal links this page is expected to expose, for the link-integrity check to prioritize. */
  expectedLinkPrefixes?: string[];
};

export const demoReviewId = "rev_gateway_42";
/** Confirmed broken in production by the 2026-09-01 UI/UX audit (P0-03) — kept as a known-bug regression id. */
export const brokenDemoReviewId = "rev_edge_ble_09";
export const demoRunId = "demo-1";
export const missingRunId = "run-does-not-exist";

export const routes: readonly QaRoute[] = [
  { id: "home", path: "/", label: "Landing", auth: "public", requiresDb: false },
  { id: "setup", path: "/setup", label: "Repository setup preview", auth: "public", requiresDb: false },
  {
    id: "reviews-list",
    path: "/reviews",
    label: "Reviews registry",
    auth: "public",
    requiresDb: false,
    expectedLinkPrefixes: ["/reviews/"],
  },
  {
    id: "review-detail",
    path: `/reviews/${demoReviewId}`,
    label: "Review detail (demo)",
    auth: "public",
    requiresDb: false,
  },
  { id: "policies", path: "/policies", label: "Governance policies", auth: "authenticated", requiresDb: false },
  { id: "evidence", path: "/evidence", label: "Evidence", auth: "public", requiresDb: false },
  { id: "insights", path: "/insights", label: "Insights", auth: "public", requiresDb: false },
  { id: "work", path: "/work", label: "My Work", auth: "authenticated", requiresDb: false },
  { id: "dashboard", path: "/dashboard", label: "Dashboard", auth: "authenticated", requiresDb: true },
  {
    id: "repository-detail",
    path: "/repositories/repo-does-not-exist",
    label: "Repository detail",
    auth: "authenticated",
    requiresDb: true,
    skipWithoutDb: true,
  },
  { id: "run-summary", path: `/runs/${demoRunId}`, label: "Run: Summary", auth: "authenticated", requiresDb: false },
  {
    id: "run-attempts",
    path: `/runs/${demoRunId}/attempts`,
    label: "Run: Attempts",
    auth: "authenticated",
    requiresDb: false,
  },
  {
    id: "run-findings",
    path: `/runs/${demoRunId}/findings`,
    label: "Run: Findings",
    auth: "authenticated",
    requiresDb: false,
  },
  {
    id: "run-artifacts",
    path: `/runs/${demoRunId}/artifacts`,
    label: "Run: Artifacts",
    auth: "authenticated",
    requiresDb: false,
  },
  {
    id: "run-publication",
    path: `/runs/${demoRunId}/publication`,
    label: "Run: Publication",
    auth: "authenticated",
    requiresDb: false,
  },
  { id: "run-audit", path: `/runs/${demoRunId}/audit`, label: "Run: Audit", auth: "authenticated", requiresDb: false },
  {
    id: "settings-billing",
    path: "/settings/billing",
    label: "Settings: Billing",
    auth: "authenticated",
    requiresDb: false,
  },
  {
    id: "settings-security",
    path: "/settings/security",
    label: "Settings: Security",
    auth: "authenticated",
    requiresDb: false,
  },
  {
    id: "settings-data",
    path: "/settings/data",
    label: "Settings: Data & Retention",
    auth: "authenticated",
    requiresDb: false,
  },
  {
    id: "settings-tokens",
    path: "/settings/tokens",
    label: "Settings: API Tokens",
    auth: "authenticated",
    requiresDb: false,
  },
  {
    id: "settings-component-intelligence",
    path: "/settings/component-intelligence",
    label: "Settings: Component Intelligence",
    auth: "authenticated",
    requiresDb: false,
  },
] as const;

/** Routes worth a screenshot baseline: high-traffic surfaces, kept short so the suite stays fast. */
export const visualRoutes: readonly string[] = [
  "home",
  "reviews-list",
  "review-detail",
  "policies",
  "settings-billing",
];

/** Not `page.tsx` routes but reachable states with their own document semantics worth auditing. */
export const errorStates = [
  { id: "not-found", path: "/this-route-does-not-exist", label: "Global 404" },
  { id: "run-not-found", path: `/runs/${missingRunId}`, label: "Run not found" },
] as const;

export function routeById(id: string): QaRoute {
  const route = routes.find((r) => r.id === id);
  if (!route) throw new Error(`Unknown QA route id: ${id}`);
  return route;
}
